version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: homies-postgres
    environment:
      POSTGRES_USER: homies_user
      POSTGRES_PASSWORD: homies_password
      POSTGRES_DB: homies_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U homies_user -d homies_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: